# Generated by Django 5.0.2 on 2024-03-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_city_order_state_order_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
